/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelUmbralesLocales.java
 *
 * Created on 29/08/2011, 10:54:26 AM
 */
package com.github.aonagarcia.igu;

import com.github.aonagarcia.extras.Instances;
import com.github.aonagarcia.extras.Utils;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import com.github.aonagarcia.svd.Control;
import com.github.aonagarcia.svd.validacionLocal.localValidation;

/**
 *
 * @author javier
 */
public class PanelUmbralesLocales extends javax.swing.JPanel {

    Control c;
    /**Objeto para mostrar los valores*/
    public datosVariablePanel dvp = new datosVariablePanel();
    /**Grafica los datos*/
    graphPanel _g = new graphPanel();
    int currentVarSelected = 0;
    /**Objeto que realiza la validaci�n local*/
    localValidation m_localValidation;
    /**Bandera para saber si ya se ha iniciado la validaci�n*/
    boolean started = false;
    int m_position;

    private Instances data;

    /** Creates new form PanelUmbralesLocales */
    public PanelUmbralesLocales(Control _control, Instances ins) {
        c = _control;
        data=ins;
         if (c._igu.m_Tabs.getSelectedIndex() == 0) {
         //if (c._igu.dp.getSelectedFrame().getName().equalsIgnoreCase("buildModel")) {
            currentVarSelected = c._igu.BuildModel.currentVarSelected;
         }
        else
            if (c._igu.m_Tabs.getSelectedIndex() == 1) {
         //if (c._igu.dp.getSelectedFrame().getName().equalsIgnoreCase("validateData")) {
            currentVarSelected = c._igu.ValidateData.currentVarSelected;
         }

        
        initComponents();
        initGraph();
        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(dvp, BorderLayout.CENTER);
        dvp.setAttributeData(AttToArray(currentVarSelected));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dataGraphPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        medianaTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        desvStdTextField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        jSlider1.setMajorTickSpacing(5);
        jSlider1.setMaximum(50);
        jSlider1.setMinimum(5);
        jSlider1.setMinorTickSpacing(5);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setValue(5);
        jSlider1.setValueIsAdjusting(true);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel1.setText("Tama�o de la ventana de an�lisis (%)");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );

        dataGraphPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Gr�fica"));

        javax.swing.GroupLayout dataGraphPanelLayout = new javax.swing.GroupLayout(dataGraphPanel);
        dataGraphPanel.setLayout(dataGraphPanelLayout);
        dataGraphPanelLayout.setHorizontalGroup(
            dataGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        dataGraphPanelLayout.setVerticalGroup(
            dataGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataGraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataGraphPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Paso a paso");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Completo");
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Mediana");

        medianaTextField.setEnabled(false);

        jLabel3.setText("Desv. Std. M.");

        desvStdTextField.setEnabled(false);

        jButton3.setText("Marcar Outliers");
        jButton3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(medianaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desvStdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton3))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(medianaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(desvStdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:        
    }//GEN-LAST:event_jSlider1StateChanged

    //Ejecuta completo el proceso de validaci�n local...
    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //jButton1.setEnabled(false);
        started = true;
        //20-06-2012 m_localValidation = new localValidation(c.BD, jSlider1.getValue());
        m_localValidation = new localValidation(data, jSlider1.getValue());
        //m_localValidation.setDelta(m_localValidation.getWindowWidthSamples());
        m_localValidation.setDelta(1);
        _g.plot.setM_graphLocalWindow(true);
        
        for (m_position = 0; m_position < data.numInstances() - m_localValidation.getWindowWidthSamples(); m_position += m_localValidation.getDelta()) {
            m_localValidation.performStepByStep(this.currentVarSelected, m_position);
            this.medianaTextField.setText(Utils.doubleToString(m_localValidation.getMediana(), 3));
            this.desvStdTextField.setText(Utils.doubleToString(m_localValidation.getDesvStdM(), 3));
            _g.plot.setOutLiersFlags(data.localOutLiers(this.currentVarSelected));
            
        }
        _g.plot.setM_localValidationWindowIni(m_position);
        _g.plot.setM_localValidationWindowFin(m_position + m_localValidation.getWindowWidthSamples());
        _g.plot.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (started == false) {
            m_localValidation = new localValidation(data, jSlider1.getValue());
            //m_localValidation.setDelta(m_localValidation.getWindowWidthSamples());
            m_localValidation.setDelta(1);
            m_position = 0;
            double[] lims=m_localValidation.performStepByStep(this.currentVarSelected, m_position);
            this.medianaTextField.setText(Utils.doubleToString(m_localValidation.getMediana(), 3));
            this.desvStdTextField.setText(Utils.doubleToString(m_localValidation.getDesvStdM(), 3));
            _g.plot.setM_graphLocalWindow(true);
            _g.plot.setUserMaxRange(lims[0]);
            _g.plot.setUserMinRange(lims[1]);
            _g.plot.setM_localValidationWindowIni(m_position);
            _g.plot.setM_localValidationWindowFin(m_position + m_localValidation.getWindowWidthSamples());
            started = true;
        } else {
            m_position += m_localValidation.getDelta();
            double[] lims=m_localValidation.performStepByStep(this.currentVarSelected, m_position);
            this.medianaTextField.setText(Utils.doubleToString(m_localValidation.getMediana(), 3));
            this.desvStdTextField.setText(Utils.doubleToString(m_localValidation.getDesvStdM(), 3));
            _g.plot.setUserMaxRange(lims[0]);
            _g.plot.setUserMinRange(lims[1]);
            _g.plot.setM_localValidationWindowIni(m_position);
            _g.plot.setM_localValidationWindowFin(m_position + m_localValidation.getWindowWidthSamples());
        }
        _g.plot.setOutLiersFlags(data.localOutLiers(this.currentVarSelected));
        _g.plot.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Objeto para marcar los outliers locales en la estructura de datos
     * @param evt
     */
    private void jButton3ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dataGraphPanel;
    private javax.swing.JTextField desvStdTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField medianaTextField;
    // End of variables declaration//GEN-END:variables

    private Object[] AttToArray(int idx) {
        Object[] _data = new Object[data.numInstances()];
        for (int k = 0; k < data.numInstances(); k++) {
            if (data.instance(k).isMissing(idx)) {
                _data[k] = (Object) null;
            } else if (data.attribute(idx).isNominal()) {
                _data[k] = (Object) data.instance(k).stringValue(idx);
            } else if (data.attribute(idx).isNumeric()) {
                _data[k] = (Object) data.instance(k).value(idx);
            }
        }
        return _data;
    }

    private void showDataSelectedSegment(int idxSgmt) {
        dvp.setAttributeData(AttToArray(idxSgmt));
        _g.resetControls();
        _g.setEnableComponents(true);
        _g.plot.setGraficarFlag(true);

        int[] arr = {idxSgmt};
        _g.plot.setAttributestoPlot(arr);
        _g.plot.setLimits(_g.calcularlimites(arr));
        _g.plot.repaint();
    }

    private void initGraph() {
        _g.setInstances(data);
        _g.plot.setGraficarFlag(true);
        _g.plot.setM_graphLocalWindow(false);
        _g.plot.setFlagLimits(false);
        _g.plot.setFlagOutOfRange(false);
        int[] arr = {this.currentVarSelected};
        _g.plot.setAttributestoPlot(arr);
        _g.plot.setLimits(_g.calcularlimites(arr));
        dataGraphPanel.setLayout(new BorderLayout());
        dataGraphPanel.add(_g, BorderLayout.CENTER);
        _g.plot.repaint();
    }
}
